/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlArea;
import java.util.ArrayList;

/**
 *
 * @author Luis
 */
public class InternalEmpleadosPorArea extends javax.swing.JInternalFrame {

    ControlArea controlArea;

    /**
     * Creates new form InternalEmpleadosPorArea
     */
    public InternalEmpleadosPorArea(ControlArea controlArea) {
        this.controlArea = controlArea;
        initComponents();
        cargarCodigosAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonConsultarEmpleados = new javax.swing.JButton();
        ComboBoxAreas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consultar empleados por area");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Seleccione el area para consultar los empleados");

        ButtonConsultarEmpleados.setText("Consultar empleados");
        ButtonConsultarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ButtonConsultarEmpleados)
                    .addComponent(ComboBoxAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonConsultarEmpleados)
                .addGap(7, 7, 7))
        );

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarEmpleadosActionPerformed
        String codigo = (String) this.ComboBoxAreas.getSelectedItem();
        ArrayList consulta = controlArea.consultarEmpleadosPorArea(codigo);
        String mensaje = "";
        int cont = 1;
        if (consulta != null) {
            for (int i = 1; i < consulta.size(); i++) {
                if (i % 5 != 0) {
                    switch (cont) {
                        case 1:
                            mensaje += "Cedula: "+(String) consulta.get(i - 1) + "\n";
                            cont++;
                            break;
                            
                        case 2: 
                             mensaje += "Nombre empleado: "+(String) consulta.get(i - 1) + "\n";
                             cont++;
                             break;
                             
                        case 3:
                             mensaje += "Nombre area: "+(String) consulta.get(i - 1) + "\n";
                             cont++;
                             break;
                             
                        case 4: 
                            mensaje += "Cargo: "+(String) consulta.get(i - 1) + "\n";
                            cont++;
                            break;
                            
                        default:
                            break;
                    }
                } else {
                    mensaje += "Salario: "+(String) consulta.get(i - 1) + "\n";
                    mensaje += "\n";
                    cont = 1;
                }

            }
            mensaje += "Salario: " + (String)consulta.get(consulta.size()-1);
            this.TextArea.setText(mensaje);
        }
    }//GEN-LAST:event_ButtonConsultarEmpleadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsultarEmpleados;
    private javax.swing.JComboBox<String> ComboBoxAreas;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarCodigosAreas() {
        ArrayList<String> consulta = controlArea.cargarCodigosAreas();
        if (consulta != null) {
            for (String codigo : consulta) {
                this.ComboBoxAreas.addItem(codigo);
            }
        }
    }
}
