/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Controlador.*;
import java.util.ArrayList;
/**
 *
 * @author Luis
 */
public class VistaMedico extends javax.swing.JFrame {
    ControlHistoriaClinica controlHistoriaClinica;
    ControlFormula controlFormula;
    ControlUsuario controlUsuario;
    ControlCita controlCita;
    ControlMedicamento controlMedicamento;
    ControlAgenda controlAgenda;
    ControlPaciente controlPaciente;
    ControlPersona controlPersona;
    ControlEnfermera controlEnfermera;
    ControlMedico controlMedico;
    ControlArea controlArea;
    ControlEmpleado controlEmpleado;
    ControlCampana controlCampana;
    ControlHistoriaClinica controlHistoria;
    ControlCama controlCama;
    ControlAsignada controlAsignada;
    ControlHabilidades controlHabilidades;
    
    
    /**
     * Creates new form VistaMedico
     */
    public VistaMedico() {
        this.controlHistoriaClinica = new ControlHistoriaClinica();
        this.controlUsuario = new ControlUsuario();
        this.controlFormula = new ControlFormula();
        this.controlMedico = new ControlMedico();
        this.controlPaciente = new ControlPaciente();
        this.controlMedicamento = new ControlMedicamento();
        initComponents();

        //Creacion de InputDialog para login
        JTextField fieldCedula = new JTextField();
        JPasswordField fieldPassword = new JPasswordField();

        JComponent[] entradas = {
            new JLabel("Cedula"),
            fieldCedula,
            new JLabel("Contraseña"),
            fieldPassword
        };//Finaliza creacion de ventana login
        boolean existe = false;
        do {
            int resultado = JOptionPane.showConfirmDialog(this, entradas, "LOGIN", JOptionPane.CANCEL_OPTION);
            if (resultado == JOptionPane.CANCEL_OPTION | resultado == JOptionPane.CLOSED_OPTION) {
                System.exit(0);
            } else if (resultado == JOptionPane.OK_OPTION) {
                String cedula = fieldCedula.getText();
                String password = new String(fieldPassword.getPassword());
                existe = controlUsuario.verificarUsuario(cedula, password, "medico");
            }
        } while (!existe);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ButtonConsultarHistoriaPaciente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonFormulaMedica = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonConsultarHistoriaPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historiaClinica.png"))); // NOI18N
        ButtonConsultarHistoriaPaciente.setText("Historia Clinica");
        ButtonConsultarHistoriaPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarHistoriaPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarHistoriaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarHistoriaPacienteActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addRegistro.png"))); // NOI18N
        jButton2.setText("Añadir registro");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(ButtonConsultarHistoriaPaciente)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonConsultarHistoriaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paciente", jPanel1);

        ButtonFormulaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/formula.png"))); // NOI18N
        ButtonFormulaMedica.setText("Emitir formula medica");
        ButtonFormulaMedica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonFormulaMedica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonFormulaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFormulaMedicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(ButtonFormulaMedica)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonFormulaMedica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Formula medica", jPanel2);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DesktopPane)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarHistoriaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarHistoriaPacienteActionPerformed
        InternalConsultarHistoriaClinica conHis = new InternalConsultarHistoriaClinica(controlHistoriaClinica);
        this.DesktopPane.add(conHis);
        conHis.show();
    }//GEN-LAST:event_ButtonConsultarHistoriaPacienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ButtonFormulaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFormulaMedicaActionPerformed
        InternalEmitirFormulaMedica emitirFormula = new InternalEmitirFormulaMedica(controlFormula, controlMedico, controlPaciente, controlMedicamento);
        this.DesktopPane.add(emitirFormula);
        emitirFormula.show();
    }//GEN-LAST:event_ButtonFormulaMedicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsultarHistoriaPaciente;
    private javax.swing.JButton ButtonFormulaMedica;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
