/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.HiloCamas;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Luis
 */
public class VistaAdmin extends javax.swing.JFrame {
    String idUsuario;
    ControlCausa controlCausa;
    ControlUsuario controlUsuario;
    ControlCita controlCita;
    ControlMedicamento controlMedicamento;
    ControlAgenda controlAgenda;
    ControlPaciente controlPaciente;
    ControlPersona controlPersona;
    ControlEnfermera controlEnfermera;
    ControlMedico controlMedico;
    ControlArea controlArea;
    ControlEmpleado controlEmpleado;
    ControlCampana controlCampana;
    ControlHistoriaClinica controlHistoria;
    ControlCama controlCama;
    ControlAsignada controlAsignada;
    ControlHabilidades controlHabilidades;
    ControlAsiste controlAsiste;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaAdmin() {
        initComponents();
        controlHabilidades = new ControlHabilidades();
        controlMedicamento = new ControlMedicamento();
        controlAsignada = new ControlAsignada();
        controlPersona = new ControlPersona();
        controlAgenda = new ControlAgenda();
        controlPaciente = new ControlPaciente();
        controlUsuario = new ControlUsuario();
        controlMedico = new ControlMedico();
        controlArea = new ControlArea();
        controlEmpleado = new ControlEmpleado();
        controlEnfermera = new ControlEnfermera();
        controlCampana = new ControlCampana();
        controlHistoria = new ControlHistoriaClinica();
        controlCita = new ControlCita();
        controlCama = new ControlCama();
        controlAsiste = new ControlAsiste();
        controlCausa = new ControlCausa();
        HiloCamas hilo = new HiloCamas(controlAsignada, controlCama);
        hilo.start();
        
        //Creacion de InputDialog para login
        JTextField fieldCedula = new JTextField();
        JPasswordField fieldPassword = new JPasswordField();
        
        JComponent[] entradas = {
            new JLabel("Cedula"),
            fieldCedula,
            new JLabel("Contraseña"),
            fieldPassword
        };//Finaliza creacion de ventana login
        String existe = null;
        do{
            int resultado = JOptionPane.showConfirmDialog(this, entradas, "LOGIN ADMINISTRADOR", JOptionPane.CANCEL_OPTION);
            if(resultado == JOptionPane.CANCEL_OPTION | resultado == JOptionPane.CLOSED_OPTION){
                System.exit(0);
            }else if(resultado == JOptionPane.OK_OPTION){
                String cedula = fieldCedula.getText();
                String password = new String(fieldPassword.getPassword());
                existe = controlUsuario.verificarUsuario(cedula, password, "Administrador");
            }
        }while(existe == null);
        idUsuario = existe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DesktopPane = new javax.swing.JDesktopPane();
        PanelPrincipal = new javax.swing.JTabbedPane();
        PanelMedico = new javax.swing.JPanel();
        ButtonAgregarMedico = new javax.swing.JButton();
        ButtonEliminarMedico = new javax.swing.JButton();
        ButtonConsultarMedico = new javax.swing.JButton();
        ButtonEditarMedico = new javax.swing.JButton();
        ButtonAgendaMes = new javax.swing.JButton();
        PanelEnfermera = new javax.swing.JPanel();
        ButtonAgregarEnfermera = new javax.swing.JButton();
        ButtonEliminarEnfermera = new javax.swing.JButton();
        ButtonConsultarEnfermera = new javax.swing.JButton();
        ButtonEditarEnfermera = new javax.swing.JButton();
        ButtonAgregarHabilidades = new javax.swing.JButton();
        PanelPaciente = new javax.swing.JPanel();
        ButtonAgregarPaciente = new javax.swing.JButton();
        ButtonEliminarPaciente = new javax.swing.JButton();
        ButtonConsultarPaciente = new javax.swing.JButton();
        ButtonEditarPaciente = new javax.swing.JButton();
        ButtonEditarPaciente1 = new javax.swing.JButton();
        ButtonEditarPaciente2 = new javax.swing.JButton();
        PanelArea = new javax.swing.JPanel();
        ButtonAgregarArea = new javax.swing.JButton();
        ButtonEliminarArea = new javax.swing.JButton();
        ButtonConsultarArea = new javax.swing.JButton();
        ButtonEditarArea = new javax.swing.JButton();
        ButtonEmpleadosPorArea = new javax.swing.JButton();
        PanelCamas = new javax.swing.JPanel();
        ButtonAgregarCama = new javax.swing.JButton();
        ButtonEliminarCama = new javax.swing.JButton();
        ButtonConsultarCama = new javax.swing.JButton();
        ButtonEditarCama = new javax.swing.JButton();
        ButtonEditarAsignarCama = new javax.swing.JButton();
        ButtonCamasAsignadas = new javax.swing.JButton();
        PanelCampana = new javax.swing.JPanel();
        ButtonAgregarCampana = new javax.swing.JButton();
        ButtonEliminarCampana = new javax.swing.JButton();
        ButtonConsultarCampana = new javax.swing.JButton();
        ButtonEditarCampana = new javax.swing.JButton();
        ButtonAgregarAsistentes = new javax.swing.JButton();
        PanelCitas = new javax.swing.JPanel();
        ButtonAgregarCita = new javax.swing.JButton();
        ButtonEliminarCita = new javax.swing.JButton();
        ButtonConsultarCita = new javax.swing.JButton();
        ButtonEditarCita = new javax.swing.JButton();
        ButtonEditarCitasPorMedico = new javax.swing.JButton();
        PanelUsuarios = new javax.swing.JPanel();
        ButtonAgregarUsuario = new javax.swing.JButton();
        ButtonEliminarUsuario = new javax.swing.JButton();
        ButtonCambiarPasswordUsuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ButtonAgregarMedicamento = new javax.swing.JButton();
        ButtonConsultarMedicamento = new javax.swing.JButton();
        ButtonEditarMedicamento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonAgregarCausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        PanelMedico.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addDoctor.png"))); // NOI18N
        ButtonAgregarMedico.setText("Agregar");
        ButtonAgregarMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarMedicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 81, 11, 0);
        PanelMedico.add(ButtonAgregarMedico, gridBagConstraints);

        ButtonEliminarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteDoctor.png"))); // NOI18N
        ButtonEliminarMedico.setText("Eliminar");
        ButtonEliminarMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarMedicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 11, 0);
        PanelMedico.add(ButtonEliminarMedico, gridBagConstraints);

        ButtonConsultarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchDoctor.png"))); // NOI18N
        ButtonConsultarMedico.setText("Consultar");
        ButtonConsultarMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarMedicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 11, 0);
        PanelMedico.add(ButtonConsultarMedico, gridBagConstraints);

        ButtonEditarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editDoctor.png"))); // NOI18N
        ButtonEditarMedico.setText("Editar");
        ButtonEditarMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarMedicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 11, 0);
        PanelMedico.add(ButtonEditarMedico, gridBagConstraints);

        ButtonAgendaMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agendaMes.png"))); // NOI18N
        ButtonAgendaMes.setText("Agenda del mes");
        ButtonAgendaMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgendaMes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgendaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendaMesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 11, 71);
        PanelMedico.add(ButtonAgendaMes, gridBagConstraints);

        PanelPrincipal.addTab("Medico", PanelMedico);

        PanelEnfermera.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addNurse.png"))); // NOI18N
        ButtonAgregarEnfermera.setText("Agregar");
        ButtonAgregarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarEnfermeraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 69, 8, 0);
        PanelEnfermera.add(ButtonAgregarEnfermera, gridBagConstraints);

        ButtonEliminarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteNurse.png"))); // NOI18N
        ButtonEliminarEnfermera.setText("Eliminar");
        ButtonEliminarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarEnfermeraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelEnfermera.add(ButtonEliminarEnfermera, gridBagConstraints);

        ButtonConsultarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchNurse.png"))); // NOI18N
        ButtonConsultarEnfermera.setText("Consultar");
        ButtonConsultarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarEnfermeraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelEnfermera.add(ButtonConsultarEnfermera, gridBagConstraints);

        ButtonEditarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editNurse.png"))); // NOI18N
        ButtonEditarEnfermera.setText("Editar");
        ButtonEditarEnfermera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarEnfermera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarEnfermeraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelEnfermera.add(ButtonEditarEnfermera, gridBagConstraints);

        ButtonAgregarHabilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregarHabilidad.png"))); // NOI18N
        ButtonAgregarHabilidades.setText("Agregar habilidades");
        ButtonAgregarHabilidades.setAutoscrolls(true);
        ButtonAgregarHabilidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarHabilidades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarHabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarHabilidadesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 76);
        PanelEnfermera.add(ButtonAgregarHabilidades, gridBagConstraints);

        PanelPrincipal.addTab("Enfermera", PanelEnfermera);

        PanelPaciente.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addPatient.png"))); // NOI18N
        ButtonAgregarPaciente.setText("Agregar");
        ButtonAgregarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 26, 8, 0);
        PanelPaciente.add(ButtonAgregarPaciente, gridBagConstraints);

        ButtonEliminarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deletePatient.png"))); // NOI18N
        ButtonEliminarPaciente.setText("Eliminar");
        ButtonEliminarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelPaciente.add(ButtonEliminarPaciente, gridBagConstraints);

        ButtonConsultarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchPatient.png"))); // NOI18N
        ButtonConsultarPaciente.setText("Consultar");
        ButtonConsultarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelPaciente.add(ButtonConsultarPaciente, gridBagConstraints);

        ButtonEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editPatient.png"))); // NOI18N
        ButtonEditarPaciente.setText("Editar");
        ButtonEditarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelPaciente.add(ButtonEditarPaciente, gridBagConstraints);

        ButtonEditarPaciente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/costoPaciente.png"))); // NOI18N
        ButtonEditarPaciente1.setText("Costo por paciente");
        ButtonEditarPaciente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarPaciente1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarPaciente1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 8, 24);
        PanelPaciente.add(ButtonEditarPaciente1, gridBagConstraints);

        ButtonEditarPaciente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sinNombreAun.png"))); // NOI18N
        ButtonEditarPaciente2.setText("Camas");
        ButtonEditarPaciente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarPaciente2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarPaciente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarPaciente2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 8, 0);
        PanelPaciente.add(ButtonEditarPaciente2, gridBagConstraints);

        PanelPrincipal.addTab("Paciente", PanelPaciente);

        PanelArea.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addArea.png"))); // NOI18N
        ButtonAgregarArea.setText("Agregar");
        ButtonAgregarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 61, 8, 0);
        PanelArea.add(ButtonAgregarArea, gridBagConstraints);

        ButtonEliminarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteArea.png"))); // NOI18N
        ButtonEliminarArea.setText("Eliminar");
        ButtonEliminarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 26, 8, 0);
        PanelArea.add(ButtonEliminarArea, gridBagConstraints);

        ButtonConsultarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchArea.png"))); // NOI18N
        ButtonConsultarArea.setText("Consultar");
        ButtonConsultarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelArea.add(ButtonConsultarArea, gridBagConstraints);

        ButtonEditarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editArea.png"))); // NOI18N
        ButtonEditarArea.setText("Editar");
        ButtonEditarArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelArea.add(ButtonEditarArea, gridBagConstraints);

        ButtonEmpleadosPorArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleados.png"))); // NOI18N
        ButtonEmpleadosPorArea.setText("Empledos por area");
        ButtonEmpleadosPorArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEmpleadosPorArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEmpleadosPorArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEmpleadosPorAreaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 82);
        PanelArea.add(ButtonEmpleadosPorArea, gridBagConstraints);

        PanelPrincipal.addTab("Area", PanelArea);

        PanelCamas.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarCama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addBed.png"))); // NOI18N
        ButtonAgregarCama.setText("Agregar");
        ButtonAgregarCama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarCama.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarCamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 8, 0);
        PanelCamas.add(ButtonAgregarCama, gridBagConstraints);

        ButtonEliminarCama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteBed.png"))); // NOI18N
        ButtonEliminarCama.setText("Eliminar");
        ButtonEliminarCama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarCama.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarCamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCamas.add(ButtonEliminarCama, gridBagConstraints);

        ButtonConsultarCama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchBed.png"))); // NOI18N
        ButtonConsultarCama.setText("Consultar");
        ButtonConsultarCama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarCama.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarCamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCamas.add(ButtonConsultarCama, gridBagConstraints);

        ButtonEditarCama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editBed.png"))); // NOI18N
        ButtonEditarCama.setText("Editar");
        ButtonEditarCama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarCama.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarCamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCamas.add(ButtonEditarCama, gridBagConstraints);

        ButtonEditarAsignarCama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/asignarCama.png"))); // NOI18N
        ButtonEditarAsignarCama.setText("Asignar cama");
        ButtonEditarAsignarCama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarAsignarCama.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarAsignarCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarAsignarCamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCamas.add(ButtonEditarAsignarCama, gridBagConstraints);

        ButtonCamasAsignadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historialCama.png"))); // NOI18N
        ButtonCamasAsignadas.setText("Historial Camas");
        ButtonCamasAsignadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCamasAsignadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonCamasAsignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCamasAsignadasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 24);
        PanelCamas.add(ButtonCamasAsignadas, gridBagConstraints);

        PanelPrincipal.addTab("Camas", PanelCamas);

        PanelCampana.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addCampaign.png"))); // NOI18N
        ButtonAgregarCampana.setText("Agregar");
        ButtonAgregarCampana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarCampana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarCampanaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 81, 8, 0);
        PanelCampana.add(ButtonAgregarCampana, gridBagConstraints);

        ButtonEliminarCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteCampaign.png"))); // NOI18N
        ButtonEliminarCampana.setText("Eliminar");
        ButtonEliminarCampana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarCampana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarCampanaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCampana.add(ButtonEliminarCampana, gridBagConstraints);

        ButtonConsultarCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchCampaign.png"))); // NOI18N
        ButtonConsultarCampana.setText("Consultar");
        ButtonConsultarCampana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarCampana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarCampanaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCampana.add(ButtonConsultarCampana, gridBagConstraints);

        ButtonEditarCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editCampaign.png"))); // NOI18N
        ButtonEditarCampana.setText("Editar");
        ButtonEditarCampana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarCampana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarCampanaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCampana.add(ButtonEditarCampana, gridBagConstraints);

        ButtonAgregarAsistentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addAsistente.png"))); // NOI18N
        ButtonAgregarAsistentes.setText("Agregar asistentes");
        ButtonAgregarAsistentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarAsistentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarAsistentesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 68);
        PanelCampana.add(ButtonAgregarAsistentes, gridBagConstraints);

        PanelPrincipal.addTab("Campaña", PanelCampana);

        PanelCitas.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addCita.png"))); // NOI18N
        ButtonAgregarCita.setText("Agregar");
        ButtonAgregarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarCitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 47, 8, 0);
        PanelCitas.add(ButtonAgregarCita, gridBagConstraints);

        ButtonEliminarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteCita.png"))); // NOI18N
        ButtonEliminarCita.setText("Eliminar");
        ButtonEliminarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarCitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCitas.add(ButtonEliminarCita, gridBagConstraints);

        ButtonConsultarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchCita.png"))); // NOI18N
        ButtonConsultarCita.setText("Consultar");
        ButtonConsultarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarCitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCitas.add(ButtonConsultarCita, gridBagConstraints);

        ButtonEditarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editCita.png"))); // NOI18N
        ButtonEditarCita.setText("Editar");
        ButtonEditarCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarCitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelCitas.add(ButtonEditarCita, gridBagConstraints);

        ButtonEditarCitasPorMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addArea.png"))); // NOI18N
        ButtonEditarCitasPorMedico.setText("Citas atendidas por medico");
        ButtonEditarCitasPorMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarCitasPorMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarCitasPorMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarCitasPorMedicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 64);
        PanelCitas.add(ButtonEditarCitasPorMedico, gridBagConstraints);

        PanelPrincipal.addTab("Citas", PanelCitas);

        PanelUsuarios.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addUser.png"))); // NOI18N
        ButtonAgregarUsuario.setText("Agregar");
        ButtonAgregarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 138, 8, 0);
        PanelUsuarios.add(ButtonAgregarUsuario, gridBagConstraints);

        ButtonEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteUser.png"))); // NOI18N
        ButtonEliminarUsuario.setText("Eliminar");
        ButtonEliminarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        PanelUsuarios.add(ButtonEliminarUsuario, gridBagConstraints);

        ButtonCambiarPasswordUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editUser.png"))); // NOI18N
        ButtonCambiarPasswordUsuario.setText("Cambiar contraseña");
        ButtonCambiarPasswordUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCambiarPasswordUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonCambiarPasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCambiarPasswordUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 152);
        PanelUsuarios.add(ButtonCambiarPasswordUsuario, gridBagConstraints);

        PanelPrincipal.addTab("Usuarios", PanelUsuarios);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        ButtonAgregarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addMedicamento.png"))); // NOI18N
        ButtonAgregarMedicamento.setText("Agregar");
        ButtonAgregarMedicamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarMedicamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarMedicamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 138, 8, 0);
        jPanel1.add(ButtonAgregarMedicamento, gridBagConstraints);

        ButtonConsultarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchMedicamentos.png"))); // NOI18N
        ButtonConsultarMedicamento.setText("Consultar");
        ButtonConsultarMedicamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarMedicamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarMedicamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 0);
        jPanel1.add(ButtonConsultarMedicamento, gridBagConstraints);

        ButtonEditarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editMedicamentos.png"))); // NOI18N
        ButtonEditarMedicamento.setText("Editar");
        ButtonEditarMedicamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditarMedicamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarMedicamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 8, 152);
        jPanel1.add(ButtonEditarMedicamento, gridBagConstraints);

        PanelPrincipal.addTab("Medicamentos", jPanel1);

        ButtonAgregarCausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addCausa.png"))); // NOI18N
        ButtonAgregarCausa.setText("Agregar");
        ButtonAgregarCausa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarCausa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarCausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(ButtonAgregarCausa)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAgregarCausa)
                .addContainerGap())
        );

        PanelPrincipal.addTab("Causas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarMedicoActionPerformed
        InternalConsultarMedico buscMed = new InternalConsultarMedico(controlMedico, controlPersona, controlEmpleado, controlArea);
        this.DesktopPane.add(buscMed);
        buscMed.show();
    }//GEN-LAST:event_ButtonConsultarMedicoActionPerformed

    private void ButtonAgregarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarMedicoActionPerformed
        InternalAgregarMedico addMed = new InternalAgregarMedico(controlMedico, controlPersona, controlEmpleado);
        this.DesktopPane.add(addMed);
        addMed.show();
    }//GEN-LAST:event_ButtonAgregarMedicoActionPerformed

    private void ButtonEliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarMedicoActionPerformed
        InternalBorrarMedico delMed = new InternalBorrarMedico(controlPersona, controlEmpleado);
        this.DesktopPane.add(delMed);
        delMed.show();
    }//GEN-LAST:event_ButtonEliminarMedicoActionPerformed

    private void ButtonEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarMedicoActionPerformed
        InternalEditarMedico editMed = new InternalEditarMedico(controlMedico, controlPersona, controlEmpleado);
        this.DesktopPane.add(editMed);
        editMed.show();
    }//GEN-LAST:event_ButtonEditarMedicoActionPerformed

    private void ButtonAgregarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarEnfermeraActionPerformed
        InternalAgregarEnfermera addEnf = new InternalAgregarEnfermera(controlEnfermera, controlEmpleado, controlPersona);
        this.DesktopPane.add(addEnf);
        addEnf.show();
    }//GEN-LAST:event_ButtonAgregarEnfermeraActionPerformed

    private void ButtonEliminarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarEnfermeraActionPerformed
        InternalBorrarEnfermera delEnf = new InternalBorrarEnfermera(controlPersona, controlEmpleado);
        this.DesktopPane.add(delEnf);
        delEnf.show();
    }//GEN-LAST:event_ButtonEliminarEnfermeraActionPerformed

    private void ButtonConsultarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarEnfermeraActionPerformed
        InternalConsultarEnfermera conEnf = new InternalConsultarEnfermera(controlEnfermera, controlEmpleado, controlPersona, controlArea, controlHabilidades);
        this.DesktopPane.add(conEnf);
        conEnf.show();
    }//GEN-LAST:event_ButtonConsultarEnfermeraActionPerformed

    private void ButtonEditarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarEnfermeraActionPerformed
        InternalEditarEnfermera editEnf =  new InternalEditarEnfermera(controlEnfermera, controlEmpleado, controlPersona);
        this.DesktopPane.add(editEnf);
        editEnf.show();
    }//GEN-LAST:event_ButtonEditarEnfermeraActionPerformed

    private void ButtonAgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarPacienteActionPerformed
        InternalAgregarPaciente addPac = new InternalAgregarPaciente(controlPaciente, controlPersona, controlHistoria);
        this.DesktopPane.add(addPac);
        addPac.show();
    }//GEN-LAST:event_ButtonAgregarPacienteActionPerformed

    private void ButtonEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarPacienteActionPerformed
        InternalBorrarPaciente delPac = new InternalBorrarPaciente(controlPersona);
        this.DesktopPane.add(delPac);
        delPac.show();
    }//GEN-LAST:event_ButtonEliminarPacienteActionPerformed

    private void ButtonConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarPacienteActionPerformed
        InternalConsultarPaciente conPac = new InternalConsultarPaciente(controlPaciente, controlPersona);
        this.DesktopPane.add(conPac);
        conPac.show();
    }//GEN-LAST:event_ButtonConsultarPacienteActionPerformed

    private void ButtonEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarPacienteActionPerformed
        InternalEditarPaciente ediPac = new InternalEditarPaciente(controlPaciente, controlPersona);
        this.DesktopPane.add(ediPac);
        ediPac.show();
    }//GEN-LAST:event_ButtonEditarPacienteActionPerformed

    private void ButtonAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarAreaActionPerformed
        InternalAgregarArea addArea = new InternalAgregarArea(controlArea);
        this.DesktopPane.add(addArea);
        addArea.show();
    }//GEN-LAST:event_ButtonAgregarAreaActionPerformed

    private void ButtonEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarAreaActionPerformed
        InternalBorrarArea delArea = new InternalBorrarArea(controlArea, controlEmpleado, controlCama);
        this.DesktopPane.add(delArea);
        delArea.show();
        
    }//GEN-LAST:event_ButtonEliminarAreaActionPerformed

    private void ButtonConsultarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarAreaActionPerformed
        InternalConsultarArea conArea = new InternalConsultarArea(controlArea);
        this.DesktopPane.add(conArea);
        conArea.show();
    }//GEN-LAST:event_ButtonConsultarAreaActionPerformed

    private void ButtonEditarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarAreaActionPerformed
        InternalEditarArea editArea = new InternalEditarArea(controlArea);
        this.DesktopPane.add(editArea);
        editArea.show();
    }//GEN-LAST:event_ButtonEditarAreaActionPerformed

    private void ButtonAgregarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarCamaActionPerformed
        InternalAgregarCama addCama = new InternalAgregarCama(controlCama);
        this.DesktopPane.add(addCama);
        addCama.show();
    }//GEN-LAST:event_ButtonAgregarCamaActionPerformed

    private void ButtonEliminarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarCamaActionPerformed
        InternalBorrarCama delCama = new InternalBorrarCama(controlCama);
        this.DesktopPane.add(delCama);
        delCama.show();
    }//GEN-LAST:event_ButtonEliminarCamaActionPerformed

    private void ButtonConsultarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarCamaActionPerformed
        InternalConsultarCama conCama = new InternalConsultarCama(controlCama, controlArea);
        this.DesktopPane.add(conCama);
        conCama.show();
    }//GEN-LAST:event_ButtonConsultarCamaActionPerformed

    private void ButtonEditarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarCamaActionPerformed
        InternalEditarCama editCama = new InternalEditarCama(controlCama);
        this.DesktopPane.add(editCama);
        editCama.show();
        
    }//GEN-LAST:event_ButtonEditarCamaActionPerformed

    private void ButtonAgregarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarCampanaActionPerformed
        InternalAgregarCampana addCamp = new InternalAgregarCampana(controlCampana, controlMedico);
        this.DesktopPane.add(addCamp);
        addCamp.show();
    }//GEN-LAST:event_ButtonAgregarCampanaActionPerformed

    private void ButtonEliminarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarCampanaActionPerformed
        InternalBorrarCampana delCamp = new InternalBorrarCampana(controlCampana);
        this.DesktopPane.add(delCamp);
        delCamp.show();
    }//GEN-LAST:event_ButtonEliminarCampanaActionPerformed

    private void ButtonConsultarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarCampanaActionPerformed
        InternalConsultarCampana conCamp = new InternalConsultarCampana(controlCampana, controlAsiste);
        this.DesktopPane.add(conCamp);
        conCamp.show();
    }//GEN-LAST:event_ButtonConsultarCampanaActionPerformed

    private void ButtonEditarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarCampanaActionPerformed
        InternalEditarCampana editCamp = new InternalEditarCampana(controlCampana, controlMedico);
        this.DesktopPane.add(editCamp);
        editCamp.show();
    }//GEN-LAST:event_ButtonEditarCampanaActionPerformed

    private void ButtonAgregarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarCitaActionPerformed
        InternalAgregarCita addCita = new InternalAgregarCita(controlCita, controlMedico, controlAgenda, controlPaciente, controlAsiste);
        this.DesktopPane.add(addCita);
        addCita.show();
    }//GEN-LAST:event_ButtonAgregarCitaActionPerformed

    private void ButtonEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarCitaActionPerformed
       InternalBorrarCita delCita = new InternalBorrarCita();
    }//GEN-LAST:event_ButtonEliminarCitaActionPerformed

    private void ButtonConsultarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConsultarCitaActionPerformed

    private void ButtonEditarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditarCitaActionPerformed

    private void ButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarUsuarioActionPerformed
        InternalAgregarUsuario addUser = new InternalAgregarUsuario(controlUsuario);
        this.DesktopPane.add(addUser);
        addUser.show();
    }//GEN-LAST:event_ButtonAgregarUsuarioActionPerformed

    private void ButtonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarUsuarioActionPerformed
        InternalBorrarUsuario delUser = new InternalBorrarUsuario(controlUsuario);
        this.DesktopPane.add(delUser);
        delUser.show();
    }//GEN-LAST:event_ButtonEliminarUsuarioActionPerformed

    private void ButtonCambiarPasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCambiarPasswordUsuarioActionPerformed
        InternalCambiarPasswordUsuario conUser = new InternalCambiarPasswordUsuario(this.idUsuario, controlUsuario);
        this.DesktopPane.add(conUser);
        conUser.show();
    }//GEN-LAST:event_ButtonCambiarPasswordUsuarioActionPerformed

    private void ButtonEmpleadosPorAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEmpleadosPorAreaActionPerformed
        InternalEmpleadosPorArea empArea = new InternalEmpleadosPorArea(controlArea);
        this.DesktopPane.add(empArea);
        empArea.show();
        
    }//GEN-LAST:event_ButtonEmpleadosPorAreaActionPerformed

    private void ButtonEditarPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarPaciente1ActionPerformed
        InternalCostoPaciente costPer = new InternalCostoPaciente(controlPaciente, controlPersona);
        this.DesktopPane.add(costPer);
        costPer.show();
    }//GEN-LAST:event_ButtonEditarPaciente1ActionPerformed

    private void ButtonEditarCitasPorMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarCitasPorMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditarCitasPorMedicoActionPerformed

    private void ButtonEditarAsignarCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarAsignarCamaActionPerformed
        InternalAsignarCama asigCama = new InternalAsignarCama(controlAsignada, controlPaciente, controlCama);
        this.DesktopPane.add(asigCama);
        asigCama.show();
    }//GEN-LAST:event_ButtonEditarAsignarCamaActionPerformed

    private void ButtonCamasAsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCamasAsignadasActionPerformed
        InternalCamasAsignadas camAsig = new InternalCamasAsignadas(controlCama,controlAsignada);
        this.DesktopPane.add(camAsig);
        camAsig.show();
    }//GEN-LAST:event_ButtonCamasAsignadasActionPerformed

    private void ButtonEditarPaciente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarPaciente2ActionPerformed
        InternalMovimientosPaciente movPac = new InternalMovimientosPaciente(controlPaciente, controlCama, controlAsignada);
        this.DesktopPane.add(movPac);
        movPac.show();
    }//GEN-LAST:event_ButtonEditarPaciente2ActionPerformed

    private void ButtonAgendaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendaMesActionPerformed
        InternalConsultarAgendaMes agendaMes = new InternalConsultarAgendaMes(controlMedico, controlAgenda);
        this.DesktopPane.add(agendaMes);
        agendaMes.show();
    }//GEN-LAST:event_ButtonAgendaMesActionPerformed

    private void ButtonAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarMedicamentoActionPerformed
        InternalAgregarMedicamento addMedi = new InternalAgregarMedicamento(controlMedicamento);
        this.DesktopPane.add(addMedi);
        addMedi.show();
    }//GEN-LAST:event_ButtonAgregarMedicamentoActionPerformed

    private void ButtonConsultarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarMedicamentoActionPerformed
        InternalConsultarMedicamento conMedi = new InternalConsultarMedicamento(controlMedicamento);
        this.DesktopPane.add(conMedi);
        conMedi.show();
    }//GEN-LAST:event_ButtonConsultarMedicamentoActionPerformed

    private void ButtonEditarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarMedicamentoActionPerformed
        InternalEditarMedicamento editMedi = new InternalEditarMedicamento(controlMedicamento);
        this.DesktopPane.add(editMedi);
        editMedi.show();
    }//GEN-LAST:event_ButtonEditarMedicamentoActionPerformed

    private void ButtonAgregarHabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarHabilidadesActionPerformed
        InternalAgregarHabilidades addHab = new InternalAgregarHabilidades(controlEnfermera, controlHabilidades);
        this.DesktopPane.add(addHab);
        addHab.show();
    }//GEN-LAST:event_ButtonAgregarHabilidadesActionPerformed

    private void ButtonAgregarAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarAsistentesActionPerformed
        InternalAgregarAsistente addAsis = new InternalAgregarAsistente(controlCampana, controlPaciente, controlAsiste);
        this.DesktopPane.add(addAsis);
        addAsis.show();
    }//GEN-LAST:event_ButtonAgregarAsistentesActionPerformed

    private void ButtonAgregarCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarCausaActionPerformed
        InternalAgregarCausa addCausa = new InternalAgregarCausa(controlCausa);
        this.DesktopPane.add(addCausa);
        addCausa.show();
    }//GEN-LAST:event_ButtonAgregarCausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendaMes;
    private javax.swing.JButton ButtonAgregarArea;
    private javax.swing.JButton ButtonAgregarAsistentes;
    private javax.swing.JButton ButtonAgregarCama;
    private javax.swing.JButton ButtonAgregarCampana;
    private javax.swing.JButton ButtonAgregarCausa;
    private javax.swing.JButton ButtonAgregarCita;
    private javax.swing.JButton ButtonAgregarEnfermera;
    private javax.swing.JButton ButtonAgregarHabilidades;
    private javax.swing.JButton ButtonAgregarMedicamento;
    private javax.swing.JButton ButtonAgregarMedico;
    private javax.swing.JButton ButtonAgregarPaciente;
    private javax.swing.JButton ButtonAgregarUsuario;
    private javax.swing.JButton ButtonCamasAsignadas;
    private javax.swing.JButton ButtonCambiarPasswordUsuario;
    private javax.swing.JButton ButtonConsultarArea;
    private javax.swing.JButton ButtonConsultarCama;
    private javax.swing.JButton ButtonConsultarCampana;
    private javax.swing.JButton ButtonConsultarCita;
    private javax.swing.JButton ButtonConsultarEnfermera;
    private javax.swing.JButton ButtonConsultarMedicamento;
    private javax.swing.JButton ButtonConsultarMedico;
    private javax.swing.JButton ButtonConsultarPaciente;
    private javax.swing.JButton ButtonEditarArea;
    private javax.swing.JButton ButtonEditarAsignarCama;
    private javax.swing.JButton ButtonEditarCama;
    private javax.swing.JButton ButtonEditarCampana;
    private javax.swing.JButton ButtonEditarCita;
    private javax.swing.JButton ButtonEditarCitasPorMedico;
    private javax.swing.JButton ButtonEditarEnfermera;
    private javax.swing.JButton ButtonEditarMedicamento;
    private javax.swing.JButton ButtonEditarMedico;
    private javax.swing.JButton ButtonEditarPaciente;
    private javax.swing.JButton ButtonEditarPaciente1;
    private javax.swing.JButton ButtonEditarPaciente2;
    private javax.swing.JButton ButtonEliminarArea;
    private javax.swing.JButton ButtonEliminarCama;
    private javax.swing.JButton ButtonEliminarCampana;
    private javax.swing.JButton ButtonEliminarCita;
    private javax.swing.JButton ButtonEliminarEnfermera;
    private javax.swing.JButton ButtonEliminarMedico;
    private javax.swing.JButton ButtonEliminarPaciente;
    private javax.swing.JButton ButtonEliminarUsuario;
    private javax.swing.JButton ButtonEmpleadosPorArea;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel PanelArea;
    private javax.swing.JPanel PanelCamas;
    private javax.swing.JPanel PanelCampana;
    private javax.swing.JPanel PanelCitas;
    private javax.swing.JPanel PanelEnfermera;
    private javax.swing.JPanel PanelMedico;
    private javax.swing.JPanel PanelPaciente;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
