/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Luis
 */
public class VistaAdmin extends javax.swing.JFrame {
    ControlUsuario controlUsuario;
    ControlPersona controlPersona;
    ControlMedico controlMedico;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaAdmin() {
        initComponents();
        controlPersona = new ControlPersona();
        controlUsuario = new ControlUsuario();
        controlMedico = new ControlMedico();
        
        //Creacion de InputDialog para login
        JTextField fieldCedula = new JTextField();
        JPasswordField fieldPassword = new JPasswordField();
        
        JComponent[] entradas = {
            new JLabel("Cedula"),
            fieldCedula,
            new JLabel("Contraseña"),
            fieldPassword
        };//Finaliza creacion de ventana login
        boolean existe = false;
        do{
            int resultado = JOptionPane.showConfirmDialog(this, entradas, "LOGIN", JOptionPane.CANCEL_OPTION);
            if(resultado == JOptionPane.CANCEL_OPTION | resultado == JOptionPane.CLOSED_OPTION){
                System.exit(0);
            }else if(resultado == JOptionPane.OK_OPTION){
                String cedula = fieldCedula.getText();
                String password = new String(fieldPassword.getPassword());
                existe = controlUsuario.consultarDatos(cedula, password);
            }
        }while(!existe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DesktopPane = new javax.swing.JDesktopPane();
        PanelPrincipal = new javax.swing.JTabbedPane();
        PanelMedico = new javax.swing.JPanel();
        ButtonAgregar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        ButtonConsultar = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        PanelEnfermera = new javax.swing.JPanel();
        PanelPaciente = new javax.swing.JPanel();
        PanelArea = new javax.swing.JPanel();
        PanelCamas = new javax.swing.JPanel();
        PanelCampana = new javax.swing.JPanel();
        PanelCitas = new javax.swing.JPanel();
        PanelUsuarios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        PanelMedico.setLayout(new java.awt.GridBagLayout());

        ButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addDoctor.png"))); // NOI18N
        ButtonAgregar.setText("Agregar");
        ButtonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 133, 3, 0);
        PanelMedico.add(ButtonAgregar, gridBagConstraints);

        ButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/deleteDoctor.png"))); // NOI18N
        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 3, 0);
        PanelMedico.add(ButtonEliminar, gridBagConstraints);

        ButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/searchDoctor.png"))); // NOI18N
        ButtonConsultar.setText("Consultar");
        ButtonConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 3, 0);
        PanelMedico.add(ButtonConsultar, gridBagConstraints);

        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editDoctor.png"))); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 3, 146);
        PanelMedico.add(ButtonEditar, gridBagConstraints);

        PanelPrincipal.addTab("Medico", PanelMedico);

        javax.swing.GroupLayout PanelEnfermeraLayout = new javax.swing.GroupLayout(PanelEnfermera);
        PanelEnfermera.setLayout(PanelEnfermeraLayout);
        PanelEnfermeraLayout.setHorizontalGroup(
            PanelEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelEnfermeraLayout.setVerticalGroup(
            PanelEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Enfermera", PanelEnfermera);

        javax.swing.GroupLayout PanelPacienteLayout = new javax.swing.GroupLayout(PanelPaciente);
        PanelPaciente.setLayout(PanelPacienteLayout);
        PanelPacienteLayout.setHorizontalGroup(
            PanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelPacienteLayout.setVerticalGroup(
            PanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Paciente", PanelPaciente);

        javax.swing.GroupLayout PanelAreaLayout = new javax.swing.GroupLayout(PanelArea);
        PanelArea.setLayout(PanelAreaLayout);
        PanelAreaLayout.setHorizontalGroup(
            PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelAreaLayout.setVerticalGroup(
            PanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Area", PanelArea);

        javax.swing.GroupLayout PanelCamasLayout = new javax.swing.GroupLayout(PanelCamas);
        PanelCamas.setLayout(PanelCamasLayout);
        PanelCamasLayout.setHorizontalGroup(
            PanelCamasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelCamasLayout.setVerticalGroup(
            PanelCamasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Camas", PanelCamas);

        javax.swing.GroupLayout PanelCampanaLayout = new javax.swing.GroupLayout(PanelCampana);
        PanelCampana.setLayout(PanelCampanaLayout);
        PanelCampanaLayout.setHorizontalGroup(
            PanelCampanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelCampanaLayout.setVerticalGroup(
            PanelCampanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Campaña", PanelCampana);

        javax.swing.GroupLayout PanelCitasLayout = new javax.swing.GroupLayout(PanelCitas);
        PanelCitas.setLayout(PanelCitasLayout);
        PanelCitasLayout.setHorizontalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelCitasLayout.setVerticalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Citas", PanelCitas);

        javax.swing.GroupLayout PanelUsuariosLayout = new javax.swing.GroupLayout(PanelUsuarios);
        PanelUsuarios.setLayout(PanelUsuariosLayout);
        PanelUsuariosLayout.setHorizontalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        PanelUsuariosLayout.setVerticalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PanelPrincipal.addTab("Usuarios", PanelUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal)
                .addContainerGap())
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarActionPerformed
        InternalBuscarMedico buscMed = new InternalBuscarMedico(controlMedico, controlPersona);
        this.DesktopPane.add(buscMed);
        buscMed.show();
    }//GEN-LAST:event_ButtonConsultarActionPerformed

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        InternalAgregarMedico addMed = new InternalAgregarMedico(controlMedico, controlPersona);
        this.DesktopPane.add(addMed);
        addMed.show();
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        InternalBorrarMedico delMed = new InternalBorrarMedico(controlMedico, controlPersona);
        this.DesktopPane.add(delMed);
        delMed.show();
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        InternalEditarMedico editMed = new InternalEditarMedico(controlMedico, controlPersona);
        this.DesktopPane.add(editMed);
        editMed.show();
    }//GEN-LAST:event_ButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonConsultar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel PanelArea;
    private javax.swing.JPanel PanelCamas;
    private javax.swing.JPanel PanelCampana;
    private javax.swing.JPanel PanelCitas;
    private javax.swing.JPanel PanelEnfermera;
    private javax.swing.JPanel PanelMedico;
    private javax.swing.JPanel PanelPaciente;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JPanel PanelUsuarios;
    // End of variables declaration//GEN-END:variables
}
