/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Controlador.*;
/**
 *
 * @author Luis
 */
public class VistaMedico extends javax.swing.JFrame {
    ControlHistoriaClinica controlHistoriaClinica;
    ControlUsuario controlUsuario;
    ControlFormula controlFormula;
    ControlMedico controlMedico;
    ControlPaciente controlPaciente;
    ControlCausa controlCausa;
    ControlMedicamento controlMedicamento;
    ControlRegistro controlRegistro;
    
    /**
     * Creates new form VistaMedico
     */
    public VistaMedico() {
        this.controlHistoriaClinica = new ControlHistoriaClinica();
        this.controlUsuario = new ControlUsuario();
        this.controlFormula = new ControlFormula();
        this.controlMedico = new ControlMedico();
        this.controlPaciente = new ControlPaciente();
        this.controlCausa = new ControlCausa();
        this.controlMedicamento = new ControlMedicamento();
        this.controlRegistro = new ControlRegistro();
        initComponents();

        //Creacion de InputDialog para login
        JTextField fieldCedula = new JTextField();
        JPasswordField fieldPassword = new JPasswordField();

        JComponent[] entradas = {
            new JLabel("Cedula"),
            fieldCedula,
            new JLabel("Contraseña"),
            fieldPassword
        };//Finaliza creacion de ventana login
        boolean existe = false;
        do {
            int resultado = JOptionPane.showConfirmDialog(this, entradas, "LOGIN", JOptionPane.CANCEL_OPTION);
            if (resultado == JOptionPane.CANCEL_OPTION | resultado == JOptionPane.CLOSED_OPTION) {
                System.exit(0);
            } else if (resultado == JOptionPane.OK_OPTION) {
                String cedula = fieldCedula.getText();
                String password = new String(fieldPassword.getPassword());
                existe = controlUsuario.verificarUsuario(cedula, password, "Médico");
            }
        } while (!existe);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ButtonConsultarHistoriaPaciente = new javax.swing.JButton();
        ButtonAgregarRegistro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonFormulaMedica = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        ButtonConsultarHistoriaPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historiaClinica.png"))); // NOI18N
        ButtonConsultarHistoriaPaciente.setText("Historia Clinica");
        ButtonConsultarHistoriaPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonConsultarHistoriaPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonConsultarHistoriaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarHistoriaPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 199, 11, 0);
        jPanel1.add(ButtonConsultarHistoriaPaciente, gridBagConstraints);

        ButtonAgregarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addRegistro.png"))); // NOI18N
        ButtonAgregarRegistro.setText("Añadir registro");
        ButtonAgregarRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAgregarRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 11, 214);
        jPanel1.add(ButtonAgregarRegistro, gridBagConstraints);

        jTabbedPane1.addTab("Paciente", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        ButtonFormulaMedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/formula.png"))); // NOI18N
        ButtonFormulaMedica.setText("Emitir formula medica");
        ButtonFormulaMedica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonFormulaMedica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonFormulaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFormulaMedicaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 243, 11, 259);
        jPanel2.add(ButtonFormulaMedica, gridBagConstraints);

        jTabbedPane1.addTab("Formula medica", jPanel2);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DesktopPane)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarHistoriaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarHistoriaPacienteActionPerformed
        InternalConsultarHistoriaClinica conHis = new InternalConsultarHistoriaClinica(controlHistoriaClinica);
        this.DesktopPane.add(conHis);
        conHis.show();
    }//GEN-LAST:event_ButtonConsultarHistoriaPacienteActionPerformed

    private void ButtonAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarRegistroActionPerformed
       InternalAgregarRegistro addReg = new InternalAgregarRegistro(controlRegistro, controlCausa, controlHistoriaClinica);
       this.DesktopPane.add(addReg);
       addReg.show();
    }//GEN-LAST:event_ButtonAgregarRegistroActionPerformed

    private void ButtonFormulaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFormulaMedicaActionPerformed
        InternalEmitirFormulaMedica emitirFormula = new InternalEmitirFormulaMedica(controlFormula, controlMedico, controlPaciente, controlMedicamento);
        this.DesktopPane.add(emitirFormula);
        emitirFormula.show();
    }//GEN-LAST:event_ButtonFormulaMedicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarRegistro;
    private javax.swing.JButton ButtonConsultarHistoriaPaciente;
    private javax.swing.JButton ButtonFormulaMedica;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
